server:
  port: 8888
  servlet:
    context-path: /EightDesciplines


spring:
  datasource:
    hikari:
      8d:
        jdbc-url: jdbc:oracle:thin:@192.168.0.217:1521:orcl
        driver-class-name: oracle.jdbc.driver.OracleDriver
        username: spfs
        password: password
      # ERP
      erp:
        jdbc-url: jdbc:oracle:thin:@10.1.100.12:1521:PROD2
        driver-class-name: oracle.jdbc.driver.OracleDriver
        username: appsclone
        password: appsclone


  thymeleaf:
    #<!-- 关闭thymeleaf缓存 开发时使用 否则没有实时画面-->
    cache: false
    ## 检查模板是否存在，然后再呈现
    check-template-location: true
    servlet:
      content-type: text/html
    #启用MVC Thymeleaf视图分辨率
    enabled: true
    #模板编码
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html
    encoding: utf-8







